### PR TITLE
Move footer and navbar to layout

### PR DESCRIPTION
**Pull request by jamos-tay**
Move footer.md and navbar.md to layout and remove all references

### CODE REVIEW

**Comment by damithc** [comment]
Let me know when it is ready for review

**Comment by jamos-tay** [comment]
I think this one should be alright for now, I'll make separate PRs for other changes

**Comment by damithc** [comment]
Netlify preview doesn't show the nav-bar/footer. The current one is using the previous version of MarkBind as the PR was created before the feature was released.

**Comment by damithc** [comment]
I checked this again today. Still doesn't work. Probably due to https://github.com/MarkBind/markbind/issues/527

**Comment by jamos-tay** [comment]
Ah, I've checked it out, apparently the all pages were switched from `page` to `default` layout, but the files in the `layout` folder weren't copied over.

**Pull request merged**
